import KalkulatorInvestasi from './KalkulatorInvestasi'
import KalkulatorLahan from './KalkulatorLahan'
import VisualGaleri from './VisualGaleri'
import PotensiSubang from './PotensiSubang'
import TimOperasional from './TimOperasional'
import { PenjagaUrl, TombolScroll } from './ScrollTanpaHash'

const asset = (file) => `/rs.subangraya/visual/${file}`

const kapasitas = [
  ['Rawat jalan', '1.600 kebutuhan', '1.620 kapasitas', 'Cadangan +20'],
  ['IGD', '160 kebutuhan', '184 kapasitas', 'Cadangan +24'],
  ['Rawat inap', '56,47 kebutuhan', '56 kapasitas', 'Hampir seimbang'],
  ['Kamar operasi', '30 kebutuhan', '48 kapasitas', 'Cadangan +18'],
  ['CT', '40 kebutuhan', '32 kapasitas', 'Optimasi kapasitas'],
]

export default function Home() {
  return (
    <>
      <style>{`
        :root{--d:#060a0d;--d2:#0b1115;--l:#f2eee5;--y:#f4c842;--g:#879298;--line:rgba(255,255,255,.12);--ok:#79dfb4;--bad:#ff806a}
        *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--d)}body{margin:0;background:var(--d);color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}.page{overflow:hidden}.wrap{max-width:1280px;margin:auto}.sec{padding:42px clamp(14px,3vw,38px);content-visibility:auto;contain-intrinsic-size:520px}.light{background:var(--l);color:var(--d)}.dark{background:var(--d);color:#fff}.soft{background:var(--d2);color:#fff}
        .nav{position:fixed;z-index:80;top:10px;left:10px;right:10px;display:flex;justify-content:space-between;gap:10px;pointer-events:none}.brand,.menu{pointer-events:auto;background:#081015;border:1px solid var(--line);border-radius:999px}.brand{padding:9px 13px;font-size:9px;font-weight:950;letter-spacing:.09em;color:#fff;cursor:pointer}.brand b{color:var(--y);margin-right:6px}.menu{display:flex;padding:3px}.menu button{border:0;background:transparent;padding:8px 9px;font-size:7px;font-weight:900;letter-spacing:.07em;color:#a2aaae;cursor:pointer}.menu button:hover{color:#fff}
        .hero{min-height:76svh;display:flex;align-items:flex-end;position:relative;background:#05090c}.hero-bg{position:absolute;inset:0;background:url('${asset('01-arrival.jpg')}') center/cover no-repeat}.hero-bg:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,7,10,.95),rgba(3,7,10,.68) 55%,rgba(3,7,10,.25)),linear-gradient(0deg,#060a0d 0%,transparent 43%)}.hero-in{position:relative;width:100%;padding:110px clamp(14px,3vw,38px) 38px}.eyebrow{font-size:8px;font-weight:950;letter-spacing:.14em;color:var(--y);text-transform:uppercase}.hero h1{font-size:clamp(40px,6vw,76px);line-height:.86;letter-spacing:-.065em;text-transform:uppercase;margin:10px 0 20px;max-width:980px}.hero h1 em{font-style:normal;color:var(--y)}.hero p{margin:0;max-width:680px;color:#cad0d3;font-size:14px;line-height:1.45}.facts{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin-top:24px}.fact{background:#091015;border:1px solid var(--line);border-radius:13px;padding:11px 12px;min-height:74px}.fact b{display:block;font-size:22px;letter-spacing:-.045em}.fact span{display:block;margin-top:5px;color:var(--g);font-size:7px;font-weight:900;line-height:1.35;letter-spacing:.05em}
        .head{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:22px}.head h2{margin:0;font-size:clamp(28px,3.8vw,44px);line-height:.92;letter-spacing:-.055em;text-transform:uppercase;max-width:780px}.head h2 em{font-style:normal;color:#a17600}.dark .head h2 em,.soft .head h2 em{color:var(--y)}.head p{margin:0;max-width:480px;font-size:10px;line-height:1.5;opacity:.62;text-align:right}
        .market{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.market article{border:1px solid rgba(6,10,13,.15);border-radius:15px;padding:14px;min-height:112px}.market article:last-child{background:var(--d);color:#fff}.market b{display:block;font-size:22px;letter-spacing:-.05em}.market span{display:block;margin-top:6px;font-size:8px;font-weight:900;line-height:1.35}.market small{display:block;margin-top:8px;font-size:7px;line-height:1.4;opacity:.55}.sources{margin:13px 0 0;font-size:7px;line-height:1.45;opacity:.58}.sources .src{font-weight:800}
        .ops-compact{border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.opline{display:grid;grid-template-columns:repeat(4,1fr);gap:0;border-bottom:1px solid var(--line)}.opline div{padding:9px 12px;border-right:1px solid var(--line)}.opline div:last-child{border-right:0}.opline b{display:block;font-size:20px;color:var(--y);letter-spacing:-.045em}.opline span{display:block;margin-top:3px;font-size:6.5px;color:var(--g);font-weight:900}.cap{display:grid;grid-template-columns:repeat(5,1fr)}.caprow{padding:9px 10px;border-right:1px solid var(--line)}.caprow:last-child{border-right:0}.caprow b{display:block;font-size:8.5px}.caprow span{display:block;font-size:7px;color:var(--g);margin-top:3px}.caprow strong{display:block;font-size:7px;color:var(--y);margin-top:3px}
        .money{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.money div{border:1px solid rgba(6,10,13,.15);border-radius:14px;padding:13px;min-height:98px}.money b{display:block;font-size:21px;letter-spacing:-.045em}.money span{display:block;margin-top:7px;font-size:7px;font-weight:900;opacity:.52;line-height:1.35}.money .key{background:var(--y)}.years{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.year{border-top:1px solid rgba(6,10,13,.15);padding:11px 3px 0}.year b{font-size:11px}.year span{display:block;font-size:8px;margin-top:5px;opacity:.58;line-height:1.45}
        .land{display:grid;grid-template-columns:1.15fr .85fr .85fr;gap:7px}.land div{border:1px solid var(--line);border-radius:14px;padding:14px;background:#0b1115}.land .utama{background:var(--y);color:var(--d);border-color:var(--y)}.land span{display:block;font-size:7px;font-weight:900;letter-spacing:.06em;color:var(--g)}.land .utama span{color:rgba(6,10,13,.58)}.land b{display:block;margin-top:5px;font-size:18px;line-height:1.05;letter-spacing:-.035em}.land p{margin:6px 0 0;font-size:8px;line-height:1.45;color:#8f999e}.land .utama p{color:rgba(6,10,13,.68)}.land-note{margin:9px 0 0;color:#8f999e;font-size:7px;line-height:1.45}
        .ready{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.ready div{border:1px solid var(--line);border-radius:14px;padding:14px}.ready b{display:block;font-size:24px;letter-spacing:-.045em}.ready span{display:block;margin-top:5px;font-size:7px;font-weight:900;color:var(--g)}.ready p{margin:7px 0 0;font-size:8px;line-height:1.45;color:#8f999e}.ready .pass b{color:var(--ok)}.gates{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:9px}.gate{border-left:2px solid var(--y);padding:7px 10px;font-size:8px;line-height:1.45;color:#9ba4a8}.gate strong{display:block;color:#fff;font-size:8px;margin-bottom:3px}
        .vg-stage{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(250px,.5fr);gap:8px;border:1px solid var(--line);border-radius:18px;overflow:hidden;background:#081015}.vg-main{position:relative;height:500px;overflow:hidden;background:#05090c}.vg-main img{width:100%;height:100%;object-fit:cover;display:block}.vg-main:before{content:'';position:absolute;inset:0;z-index:1;background:linear-gradient(90deg,rgba(4,8,10,.12),transparent 58%),linear-gradient(0deg,rgba(4,8,10,.92),transparent 45%);pointer-events:none}.vg-label{position:absolute;z-index:2;left:20px;right:20px;bottom:18px;display:flex;justify-content:space-between;align-items:end;gap:18px}.vg-label div{display:flex;flex-direction:column;gap:5px}.vg-label span{font-size:7px;font-weight:950;letter-spacing:.13em;color:var(--y)}.vg-label b{font-size:clamp(30px,4.5vw,58px);line-height:.86;letter-spacing:-.055em;text-transform:uppercase}.vg-label strong{font-size:8px;letter-spacing:.1em;color:#c2c9cc}.vg-list{height:500px;overflow:auto;padding:8px;display:flex;flex-direction:column;gap:5px;scrollbar-width:thin}.vg-list button{min-height:52px;border:1px solid var(--line);border-radius:11px;padding:9px 10px;background:transparent;color:#fff;cursor:pointer;text-align:left;display:flex;justify-content:space-between;align-items:center;gap:10px}.vg-list button.aktif{background:var(--y);color:var(--d);border-color:var(--y)}.vg-list button div{min-width:0}.vg-list small{display:block;font-size:6px;letter-spacing:.08em;color:var(--g);margin-bottom:3px}.vg-list button.aktif small{color:rgba(6,10,13,.56)}.vg-list b{display:block;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.vg-list span{font-size:7px;color:var(--g);font-weight:900}.vg-list button.aktif span{color:rgba(6,10,13,.56)}.closing{padding:40px clamp(14px,3vw,38px);background:var(--y);color:var(--d)}.closein{max-width:1280px;margin:auto;display:flex;justify-content:space-between;gap:20px;align-items:center}.closing h2{font-size:clamp(26px,3.4vw,38px);margin:0;letter-spacing:-.055em;text-transform:uppercase}.closing button{border:1px solid var(--d);background:transparent;color:var(--d);border-radius:999px;padding:11px 15px;font-size:8px;font-weight:950;white-space:nowrap;cursor:pointer}
        @media(max-width:900px){.facts,.market{grid-template-columns:repeat(2,1fr)}.market article:last-child{grid-column:span 2}.money{grid-template-columns:repeat(3,1fr)}.head{display:block}.head p{text-align:left;margin-top:8px}.cap{grid-template-columns:repeat(3,1fr)}.caprow{border-bottom:1px solid var(--line)}}
        @media(max-width:620px){.menu{display:none}.hero{min-height:68svh}.hero h1{font-size:40px}.facts{grid-template-columns:repeat(2,1fr)}.fact:last-child{grid-column:span 2}.sec{padding:28px 13px}.head{margin-bottom:14px}.head h2{font-size:28px}.market{grid-template-columns:1fr 1fr}.opline{grid-template-columns:1fr 1fr}.opline div:nth-child(2){border-right:0}.opline div:nth-child(-n+2){border-bottom:1px solid var(--line)}.cap{grid-template-columns:1fr 1fr}.caprow{border-bottom:1px solid var(--line)}.money{grid-template-columns:1fr 1fr}.years,.ready,.gates,.land{grid-template-columns:1fr}.vg-stage{grid-template-columns:1fr}.vg-main{height:330px}.vg-list{height:auto;max-height:240px;display:grid;grid-template-columns:1fr 1fr}.vg-list button{min-height:54px}.closein{display:block}.closing button{display:inline-block;margin-top:14px}}
      `}</style>

      <div className="page">
        <PenjagaUrl /><nav className="nav"><TombolScroll className="brand" target="atas"><b>+</b>RS SUBANG RAYA</TombolScroll><div className="menu"><TombolScroll target="subang">SUBANG</TombolScroll><TombolScroll target="operasi">OPERASI</TombolScroll><TombolScroll target="ekonomi">KEUANGAN</TombolScroll><TombolScroll target="kesiapan">KESIAPAN</TombolScroll><TombolScroll target="kalkulator-investasi">INVESTASI</TombolScroll></div></nav>

        <header id="atas" className="hero"><div className="hero-bg"/><div className="wrap hero-in"><div className="eyebrow">Presentasi Investor · RS Subang Raya</div><h1>Rumah sakit untuk <em>pertumbuhan Subang.</em></h1><p>Ringkasan investor berbasis angka proyek terkendali, kapasitas layanan, dan potensi pertumbuhan Subang.</p><div className="facts"><div className="fact"><b>66</b><span>POSISI PASIEN</span></div><div className="fact"><b>6</b><span>KAMAR OPERASI</span></div><div className="fact"><b>&gt;2.000</b><span>TARGET KUNJUNGAN / HARI</span></div><div className="fact"><b>Rp861,1 M</b><span>CAPEX DASAR</span></div><div className="fact"><b>0%</b><span>UTANG BANK · SKENARIO UTAMA</span></div><div className="fact"><b>±700</b><span>SDM OPERASIONAL</span></div></div></div></header>

        <PotensiSubang />

        <section id="operasi" className="sec dark"><div className="wrap"><div className="head"><h2>Kapasitas <em>layanan</em></h2><p>Angka inti yang mempengaruhi volume dan keputusan investasi.</p></div><div className="ops-compact"><div className="opline"><div><b>56 + 10</b><span>RAWAT INAP + ICU · 66 POSISI</span></div><div><b>6 / 8 / 10</b><span>OR / PRAOPERASI / PACU</span></div><div><b>371</b><span>BASIS RUANG TEKNIS</span></div><div><b>≥658</b><span>MINIMUM TITIK DATA</span></div></div><div className="cap">{kapasitas.map(([nama,butuh,mampu,status]) => <div className="caprow" key={nama}><b>{nama}</b><span>{butuh} · {mampu}</span><strong>{status}</strong></div>)}</div></div></div></section>

        <TimOperasional />

        <section id="ekonomi" className="sec light"><div className="wrap"><div className="head"><h2>Ekonomi <em>proyek</em></h2><p>Model investasi menggunakan satu basis CAPEX terkendali secara konsisten dari pembangunan sampai valuasi Tahun 10.</p></div><div className="money"><div className="key"><b>Rp861,1 M</b><span>CAPEX DASAR</span></div><div><b>Rp1,30 T</b><span>PENDAPATAN TAHUN 4</span></div><div><b>Rp162,5 M</b><span>EBITDA TAHUN 4</span></div><div><b>Rp1,742 T</b><span>PENDAPATAN TAHUN 10</span></div><div><b>Rp243,9 M</b><span>EBITDA TAHUN 10</span></div><div><b>Rp2,439 T</b><span>NILAI EKUITAS TAHUN 10 · MODEL 0% BANK</span></div></div><div className="years"><div className="year"><b>TAHUN 1</b><span>900 kunjungan/hari · pendapatan Rp585 M · EBITDA -Rp29,25 M</span></div><div className="year"><b>TAHUN 4</b><span>2.000 kunjungan/hari · pendapatan Rp1,30 T · EBITDA Rp162,5 M</span></div><div className="year"><b>TAHUN 10</b><span>2.680 kunjungan/hari · pendapatan Rp1,742 T · EBITDA Rp243,9 M</span></div></div></div></section>

        <KalkulatorLahan />

        <section id="kesiapan" className="sec soft"><div className="wrap"><div className="head"><h2>Kesiapan <em>proyek</em></h2><p>Perencanaan dikendalikan melalui model internal, BOQ, program ruang, dan rangka verifikasi eksternal.</p></div><div className="ready"><div className="pass"><b>LULUS</b><span>QA MODEL INTERNAL</span><p>Model, asumsi, dan kontrol internal telah melalui pemeriksaan.</p></div><div><b>164</b><span>ITEM BOQ TERKENDALI</span><p>Basis biaya proyek ditelusuri pada daftar item terkontrol.</p></div><div><b>371</b><span>RUANG TEKNIS</span><p>Program ruang menjadi basis koordinasi arsitektur dan engineering.</p></div></div><div className="gates"><div className="gate"><strong>11 GATE PENGENDALIAN</strong>Verifikasi eksternal dikelola dari survey, struktur, keselamatan, peralatan, biaya, sampai perizinan.</div><div className="gate"><strong>66 POSISI PASIEN</strong>56 rawat inap + 10 ICU menjadi basis kapasitas pasien.</div><div className="gate"><strong>6 KAMAR OPERASI</strong>Didukung 8 praoperasi dan 10 PACU pada basis program layanan.</div></div></div></section>

        <section className="sec dark"><div className="wrap"><div className="head"><h2>Konsep <em>layanan</em></h2><p>Visual ruang utama yang menggambarkan pengalaman pasien, alur layanan, dan kualitas fasilitas RS Subang Raya.</p></div><VisualGaleri /></div></section>

        <div className="closing"><div className="closein"><h2>Lihat porsi investasi Anda.</h2><TombolScroll target="kalkulator-investasi">BUKA PERHITUNGAN ↓</TombolScroll></div></div>
      </div>
      <KalkulatorInvestasi />
    </>
  )
}
