import KalkulatorInvestasi from './KalkulatorInvestasi'
import VisualGaleri from './VisualGaleri'
import { PenjagaUrl, TombolScroll } from './ScrollTanpaHash'

const asset = (file) => `/rs.subangraya/visual/${file}`

const kapasitas = [
  ['Rawat jalan', '1.600 kebutuhan', '1.620 kapasitas', 'Ketat'],
  ['IGD', '160 kebutuhan', '184 kapasitas', 'Longgar'],
  ['Rawat inap', '56,47 kebutuhan', '56 kapasitas', 'Batas'],
  ['Kamar operasi', '30 kebutuhan', '48 kapasitas', 'Longgar'],
  ['CT', '40 kebutuhan', '32 kapasitas', 'Kendala'],
]

export default function Home() {
  return (
    <>
      <style>{`
        :root{--d:#060a0d;--d2:#0b1115;--l:#f2eee5;--y:#f4c842;--g:#879298;--line:rgba(255,255,255,.12);--ok:#79dfb4;--bad:#ff806a}
        *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--d)}body{margin:0;background:var(--d);color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}.page{overflow:hidden}.wrap{max-width:1280px;margin:auto}.sec{padding:42px clamp(14px,3vw,38px)}.light{background:var(--l);color:var(--d)}.dark{background:var(--d);color:#fff}.soft{background:var(--d2);color:#fff}
        .nav{position:fixed;z-index:80;top:10px;left:10px;right:10px;display:flex;justify-content:space-between;gap:10px;pointer-events:none}.brand,.menu{pointer-events:auto;background:#081015;border:1px solid var(--line);border-radius:999px}.brand{padding:9px 13px;font-size:9px;font-weight:950;letter-spacing:.09em;color:#fff;cursor:pointer}.brand b{color:var(--y);margin-right:6px}.menu{display:flex;padding:3px}.menu button{border:0;background:transparent;padding:8px 9px;font-size:7px;font-weight:900;letter-spacing:.07em;color:#a2aaae;cursor:pointer}.menu button:hover{color:#fff}
        .hero{min-height:76svh;display:flex;align-items:flex-end;position:relative;background:#05090c}.hero-bg{position:absolute;inset:0;background:url('${asset('01-arrival.jpg')}') center/cover no-repeat}.hero-bg:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,7,10,.95),rgba(3,7,10,.68) 55%,rgba(3,7,10,.25)),linear-gradient(0deg,#060a0d 0%,transparent 43%)}.hero-in{position:relative;width:100%;padding:110px clamp(14px,3vw,38px) 38px}.eyebrow{font-size:8px;font-weight:950;letter-spacing:.14em;color:var(--y);text-transform:uppercase}.hero h1{font-size:clamp(40px,6vw,76px);line-height:.86;letter-spacing:-.065em;text-transform:uppercase;margin:10px 0 20px;max-width:980px}.hero h1 em{font-style:normal;color:var(--y)}.hero p{margin:0;max-width:680px;color:#cad0d3;font-size:14px;line-height:1.45}.facts{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:24px}.fact{background:#091015;border:1px solid var(--line);border-radius:13px;padding:11px 12px;min-height:74px}.fact b{display:block;font-size:22px;letter-spacing:-.045em}.fact span{display:block;margin-top:5px;color:var(--g);font-size:7px;font-weight:900;line-height:1.35;letter-spacing:.05em}
        .head{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:22px}.head h2{margin:0;font-size:clamp(28px,3.8vw,44px);line-height:.92;letter-spacing:-.055em;text-transform:uppercase;max-width:780px}.head h2 em{font-style:normal;color:#a17600}.dark .head h2 em,.soft .head h2 em{color:var(--y)}.head p{margin:0;max-width:480px;font-size:10px;line-height:1.5;opacity:.62;text-align:right}
        .market{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.market article{border:1px solid rgba(6,10,13,.15);border-radius:15px;padding:14px;min-height:112px}.market article:last-child{background:var(--d);color:#fff}.market b{display:block;font-size:22px;letter-spacing:-.05em}.market span{display:block;margin-top:6px;font-size:8px;font-weight:900;line-height:1.35}.market small{display:block;margin-top:8px;font-size:7px;line-height:1.4;opacity:.55}.sources{margin:13px 0 0;font-size:7px;line-height:1.45;opacity:.58}.sources .src{font-weight:800}
        .staff{display:grid;grid-template-columns:1fr 1fr 1.5fr;gap:7px;margin-top:18px}.staff div{border:1px solid rgba(6,10,13,.15);border-radius:13px;padding:13px}.staff b{display:block;font-size:18px}.staff span{display:block;font-size:7px;font-weight:900;opacity:.52;margin-bottom:5px}.staff p{margin:0;font-size:8px;line-height:1.45;opacity:.62}.pending{color:#986316}
        .ops{display:grid;grid-template-columns:.92fr 1.08fr;gap:32px}.opfacts{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.opfacts div{border:1px solid var(--line);border-radius:14px;padding:13px;min-height:90px}.opfacts b{display:block;font-size:26px;color:var(--y);letter-spacing:-.05em}.opfacts span{display:block;margin-top:6px;font-size:7px;line-height:1.35;color:var(--g);font-weight:900}.cap{border-top:1px solid var(--line)}.caprow{display:grid;grid-template-columns:110px 1fr 105px;gap:12px;align-items:center;padding:11px 0;border-bottom:1px solid var(--line)}.caprow b{font-size:9px}.caprow span{font-size:8px;color:var(--g)}.caprow strong{font-size:8px;text-align:right}.caprow:last-child strong{color:var(--bad)}
        .money{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.money div{border:1px solid rgba(6,10,13,.15);border-radius:14px;padding:13px;min-height:98px}.money b{display:block;font-size:21px;letter-spacing:-.045em}.money span{display:block;margin-top:7px;font-size:7px;font-weight:900;opacity:.52;line-height:1.35}.money .key{background:var(--y)}.years{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.year{border-top:1px solid rgba(6,10,13,.15);padding:11px 3px 0}.year b{font-size:11px}.year span{display:block;font-size:8px;margin-top:5px;opacity:.58;line-height:1.45}
        .land{display:grid;grid-template-columns:1.15fr .85fr .85fr;gap:7px}.land div{border:1px solid var(--line);border-radius:14px;padding:14px;background:#0b1115}.land .utama{background:var(--y);color:var(--d);border-color:var(--y)}.land span{display:block;font-size:7px;font-weight:900;letter-spacing:.06em;color:var(--g)}.land .utama span{color:rgba(6,10,13,.58)}.land b{display:block;margin-top:5px;font-size:18px;line-height:1.05;letter-spacing:-.035em}.land p{margin:6px 0 0;font-size:8px;line-height:1.45;color:#8f999e}.land .utama p{color:rgba(6,10,13,.68)}.land-note{margin:9px 0 0;color:#8f999e;font-size:7px;line-height:1.45}
        .ready{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.ready div{border:1px solid var(--line);border-radius:14px;padding:14px}.ready b{display:block;font-size:24px;letter-spacing:-.045em}.ready span{display:block;margin-top:5px;font-size:7px;font-weight:900;color:var(--g)}.ready p{margin:7px 0 0;font-size:8px;line-height:1.45;color:#8f999e}.ready .pass b{color:var(--ok)}.ready .open b{color:var(--y)}.gates{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:9px}.gate{border-left:2px solid var(--y);padding:7px 10px;font-size:8px;line-height:1.45;color:#9ba4a8}.gate strong{display:block;color:#fff;font-size:8px;margin-bottom:3px}
        .vg-stage{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(250px,.5fr);gap:8px;border:1px solid var(--line);border-radius:18px;overflow:hidden;background:#081015}.vg-main{position:relative;height:500px;overflow:hidden;background:#05090c}.vg-main img{width:100%;height:100%;object-fit:cover;display:block}.vg-main:before{content:'';position:absolute;inset:0;z-index:1;background:linear-gradient(90deg,rgba(4,8,10,.12),transparent 58%),linear-gradient(0deg,rgba(4,8,10,.92),transparent 45%);pointer-events:none}.vg-label{position:absolute;z-index:2;left:20px;right:20px;bottom:18px;display:flex;justify-content:space-between;align-items:end;gap:18px}.vg-label div{display:flex;flex-direction:column;gap:5px}.vg-label span{font-size:7px;font-weight:950;letter-spacing:.13em;color:var(--y)}.vg-label b{font-size:clamp(30px,4.5vw,58px);line-height:.86;letter-spacing:-.055em;text-transform:uppercase}.vg-label strong{font-size:8px;letter-spacing:.1em;color:#c2c9cc}.vg-list{height:500px;overflow:auto;padding:8px;display:flex;flex-direction:column;gap:5px;scrollbar-width:thin}.vg-list button{min-height:52px;border:1px solid var(--line);border-radius:11px;padding:9px 10px;background:transparent;color:#fff;cursor:pointer;text-align:left;display:flex;justify-content:space-between;align-items:center;gap:10px}.vg-list button.aktif{background:var(--y);color:var(--d);border-color:var(--y)}.vg-list button div{min-width:0}.vg-list small{display:block;font-size:6px;letter-spacing:.08em;color:var(--g);margin-bottom:3px}.vg-list button.aktif small{color:rgba(6,10,13,.56)}.vg-list b{display:block;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.vg-list span{font-size:7px;color:var(--g);font-weight:900}.vg-list button.aktif span{color:rgba(6,10,13,.56)}.closing{padding:40px clamp(14px,3vw,38px);background:var(--y);color:var(--d)}.closein{max-width:1280px;margin:auto;display:flex;justify-content:space-between;gap:20px;align-items:center}.closing h2{font-size:clamp(26px,3.4vw,38px);margin:0;letter-spacing:-.055em;text-transform:uppercase}.closing button{border:1px solid var(--d);background:transparent;color:var(--d);border-radius:999px;padding:11px 15px;font-size:8px;font-weight:950;white-space:nowrap;cursor:pointer}
        @media(max-width:900px){.facts,.market{grid-template-columns:repeat(2,1fr)}.market article:last-child{grid-column:span 2}.ops{grid-template-columns:1fr}.money{grid-template-columns:repeat(3,1fr)}.head{display:block}.head p{text-align:left;margin-top:8px}.staff{grid-template-columns:1fr 1fr}.staff div:last-child{grid-column:span 2}}
        @media(max-width:620px){.menu{display:none}.hero{min-height:68svh}.hero h1{font-size:40px}.facts{grid-template-columns:repeat(2,1fr)}.fact:last-child{grid-column:span 2}.sec{padding:32px 13px}.head h2{font-size:28px}.market{grid-template-columns:1fr 1fr}.opfacts{grid-template-columns:1fr 1fr}.caprow{grid-template-columns:82px 1fr 72px}.money{grid-template-columns:1fr 1fr}.years,.ready,.gates,.land{grid-template-columns:1fr}.vg-stage{grid-template-columns:1fr}.vg-main{height:330px}.vg-list{height:auto;max-height:240px;display:grid;grid-template-columns:1fr 1fr}.vg-list button{min-height:54px}.closein{display:block}.closing button{display:inline-block;margin-top:14px}.staff{grid-template-columns:1fr}.staff div:last-child{grid-column:auto}}
      `}</style>

      <div className="page">
        <PenjagaUrl /><nav className="nav"><TombolScroll className="brand" target="atas"><b>+</b>RS SUBANG RAYA</TombolScroll><div className="menu"><TombolScroll target="subang">SUBANG</TombolScroll><TombolScroll target="operasi">OPERASI</TombolScroll><TombolScroll target="ekonomi">KEUANGAN</TombolScroll><TombolScroll target="kesiapan">KESIAPAN</TombolScroll><TombolScroll target="kalkulator-investasi">INVESTASI</TombolScroll></div></nav>

        <header id="atas" className="hero"><div className="hero-bg"/><div className="wrap hero-in"><div className="eyebrow">Presentasi Investor · RS Subang Raya</div><h1>Rumah sakit untuk <em>pertumbuhan Subang.</em></h1><p>Ringkasan investor berbasis angka proyek terkendali dan data publik resmi. Tidak ada angka SDM proyek yang dibuat sebelum formasi dan roster disahkan.</p><div className="facts"><div className="fact"><b>66</b><span>POSISI PASIEN</span></div><div className="fact"><b>6</b><span>KAMAR OPERASI</span></div><div className="fact"><b>&gt;2.000</b><span>TARGET KUNJUNGAN / HARI</span></div><div className="fact"><b>Rp861,1 M</b><span>CAPEX DASAR</span></div><div className="fact"><b>0%</b><span>UTANG BANK · SKENARIO UTAMA</span></div></div></div></header>

        <section id="subang" className="sec light"><div className="wrap"><div className="head"><h2>Potensi <em>Subang</em></h2><p>Data pasar di bawah adalah data publik wilayah, bukan angka internal RS Subang Raya.</p></div><div className="market"><article><b>1.675.519</b><span>PENDUDUK KABUPATEN SUBANG</span><small>Basis indikator Kemenkes · sumber populasi BPS 2024</small></article><article><b>629</b><span>DOKTER UMUM + SPESIALIS</span><small>477 umum + 152 spesialis · Kemenkes</small></article><article><b>1.842</b><span>PERAWAT</span><small>Indikator SDM kesehatan Kemenkes</small></article><article><b>1.232</b><span>BIDAN</span><small>Indikator SDM kesehatan Kemenkes</small></article><article><b>284.521</b><span>BURUH / KARYAWAN / PEGAWAI</span><small>Pasar tenaga kerja Subang · BPS 2024</small></article><article><b>10 + 1 + 40</b><span>RS UMUM + RS BERSALIN + PUSKESMAS</span><small>Fasilitas kesehatan Subang · BPS 2024</small></article></div><div className="staff"><div><span>DOKTER RS SUBANG RAYA</span><b className="pending">BELUM DIKUNCI</b></div><div><span>TOTAL KARYAWAN RS SUBANG RAYA</span><b className="pending">BELUM DIKUNCI</b></div><div><span>ALASAN</span><p>Formasi, FTE, shift, rekrutmen dan opening roster masih berstatus OPEN. Angka baru ditampilkan setelah bukti SDM disetujui.</p></div></div><p className="sources"><strong>Rebana + Patimban:</strong> pengembangan kawasan industri dan logistik terintegrasi Pelabuhan Patimban. · Sumber publik: <span className="src">BPS Kabupaten Subang Dalam Angka 2025</span> · <span className="src">Kemenkes SISDMK</span> · <span className="src">Pemkab Subang — Rebana/Patimban</span>.</p></div></section>

        <section id="operasi" className="sec dark"><div className="wrap"><div className="head"><h2>Kapasitas <em>layanan</em></h2><p>Angka inti yang mempengaruhi volume dan keputusan investasi.</p></div><div className="ops"><div className="opfacts"><div><b>56 + 10</b><span>RAWAT INAP + ICU = 66 POSISI</span></div><div><b>6 / 8 / 10</b><span>OR / PRAOPERASI / PACU</span></div><div><b>371</b><span>BASIS RUANG TEKNIS</span></div><div><b>≥658</b><span>MINIMUM TITIK DATA</span></div></div><div className="cap">{kapasitas.map(([nama,butuh,mampu,status]) => <div className="caprow" key={nama}><b>{nama}</b><span>{butuh} · {mampu}</span><strong>{status}</strong></div>)}</div></div></div></section>

        <section id="ekonomi" className="sec light"><div className="wrap"><div className="head"><h2>Ekonomi <em>proyek</em></h2><p>CAPEX masih anggaran perencanaan, belum biaya tersertifikasi.</p></div><div className="money"><div className="key"><b>Rp861,1 M</b><span>CAPEX DASAR</span></div><div><b>Rp1,30 T</b><span>PENDAPATAN TAHUN 4</span></div><div><b>Rp162,5 M</b><span>EBITDA TAHUN 4</span></div><div><b>Rp1,742 T</b><span>PENDAPATAN TAHUN 10</span></div><div><b>Rp243,9 M</b><span>EBITDA TAHUN 10</span></div><div><b>Rp2,439 T</b><span>NILAI EKUITAS TAHUN 10 · MODEL 0% BANK</span></div></div><div className="years"><div className="year"><b>TAHUN 1</b><span>900 kunjungan/hari · pendapatan Rp585 M · EBITDA -Rp29,25 M</span></div><div className="year"><b>TAHUN 4</b><span>2.000 kunjungan/hari · pendapatan Rp1,30 T · EBITDA Rp162,5 M</span></div><div className="year"><b>TAHUN 10</b><span>2.680 kunjungan/hari · pendapatan Rp1,742 T · EBITDA Rp243,9 M</span></div></div></div></section>

        <section id="investor-lahan" className="sec dark"><div className="wrap"><div className="head"><h2>Investor <em>lahan</em></h2><p>Skema pembayaran pemilik lahan berdasarkan arahan pemilik proyek.</p></div><div className="land"><div className="utama"><span>PEMBAYARAN LAHAN</span><b>TUNAI + 30% NILAI TANAH</b><p>Harga pembelian tanah dibayar tunai, ditambah 30% dari nilai tanah yang disepakati. Jika tunai = 100% nilai tanah, total pembayaran = 130% nilai tanah.</p></div><div><span>PEMICU 1</span><b>INVESTOR 100%</b><p>Pembayaran dilakukan setelah pendanaan investor proyek mencapai 100%.</p></div><div><span>PEMICU 2 · CADANGAN</span><b>BANK CAIR</b><p>Jika investor belum terpenuhi, pembayaran dilakukan saat pengajuan pembiayaan bank cair.</p></div></div><p className="land-note">Nilai rupiah tanah belum ditampilkan sampai nilai tanah disepakati dan divalidasi. Jalur bank adalah pemicu cadangan pembayaran lahan bila target investor belum lengkap; skenario utama presentasi investor tetap 0% utang bank.</p></div></section>

        <section id="kesiapan" className="sec soft"><div className="wrap"><div className="head"><h2>Status <em>kesiapan</em></h2><p>Hanya status yang mempengaruhi keputusan investor ditampilkan.</p></div><div className="ready"><div className="pass"><b>LULUS</b><span>QA MODEL INTERNAL</span><p>Model, asumsi dan kontrol internal telah diperiksa.</p></div><div className="open"><b>0 / 11</b><span>GATE EKSTERNAL TERTUTUP</span><p>Bukti eksternal masih harus ditutup sebelum rilis final.</p></div><div className="open"><b>OPEN</b><span>FORMASI & ROSTER SDM</span><p>Total dokter dan karyawan proyek belum boleh diklaim sebagai angka final.</p></div></div><div className="gates"><div className="gate"><strong>T09 · Program klinis</strong>0 / 371 persetujuan ruang.</div><div className="gate"><strong>T10 · Biaya</strong>BOQ terukur & rekonsiliasi QS/Keuangan masih terbuka.</div><div className="gate"><strong>T11 · Perizinan</strong>Bukti persetujuan otoritas masih terbuka.</div></div></div></section>

        <section className="sec dark"><div className="wrap"><div className="head"><h2>Konsep <em>layanan</em></h2><p>Galeri konsep layanan dengan pilihan ruang utama. Tetap tanpa 3D aktif agar presentasi ringan.</p></div><VisualGaleri /></div></section>

        <div className="closing"><div className="closein"><h2>Lihat porsi investasi Anda.</h2><TombolScroll target="kalkulator-investasi">BUKA PERHITUNGAN ↓</TombolScroll></div></div>
      </div>
      <KalkulatorInvestasi />
    </>
  )
}
