const asset = (file) => `/rs.subangraya/visual/${file}`

export default function PotensiSubang(){
  return <section id="subang" className="ps">
    <style>{`
      .ps{background:#f2eee5;color:#060a0d;padding:42px clamp(14px,3vw,38px);content-visibility:auto;contain-intrinsic-size:760px}.ps-in{max-width:1280px;margin:auto}.ps-head{display:flex;justify-content:space-between;align-items:end;gap:28px;margin-bottom:18px}.ps-head h2{margin:0;font-size:clamp(32px,4.3vw,52px);line-height:.9;letter-spacing:-.06em;text-transform:uppercase}.ps-head h2 em{font-style:normal;color:#a17600}.ps-head p{margin:0;max-width:520px;text-align:right;font-size:11px;line-height:1.45;color:#5f625f}
      .ps-visuals{display:grid;grid-template-columns:1.45fr .8fr;grid-template-rows:220px 220px;gap:8px}.ps-card{position:relative;overflow:hidden;border-radius:18px;background:#101417;color:#fff}.ps-card.big{grid-row:1/3}.ps-card img{width:100%;height:100%;object-fit:cover;display:block}.ps-card:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(4,8,10,.05) 20%,rgba(4,8,10,.88) 100%)}.ps-copy{position:absolute;z-index:2;left:18px;right:18px;bottom:16px}.ps-copy span{font-size:7px;font-weight:950;letter-spacing:.12em;color:#f4c842;text-transform:uppercase}.ps-copy h3{margin:5px 0 4px;font-size:clamp(23px,3vw,40px);line-height:.9;letter-spacing:-.05em;text-transform:uppercase}.ps-card:not(.big) .ps-copy h3{font-size:24px}.ps-copy p{margin:0;max-width:650px;color:#d8dddf;font-size:9px;line-height:1.4}.ps-source{position:absolute;z-index:2;right:12px;top:12px;background:rgba(5,9,12,.72);border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:6px 8px;color:#cbd2d5;font-size:6px;font-weight:900;letter-spacing:.07em}
    `}</style>    <style>{`
      .ps-numbers{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:8px}.ps-stat{border:1px solid rgba(6,10,13,.14);border-radius:15px;padding:13px 14px;background:#f8f5ef;min-height:92px}.ps-stat b{display:block;font-size:clamp(20px,2.5vw,31px);line-height:1;letter-spacing:-.05em;font-variant-numeric:tabular-nums}.ps-stat span{display:block;margin-top:7px;font-size:7px;font-weight:950;letter-spacing:.04em;line-height:1.35}.ps-stat small{display:block;margin-top:5px;font-size:6.5px;line-height:1.4;color:#6e716f}.ps-stat.dark{background:#060a0d;color:#fff;border-color:#060a0d}.ps-stat.dark small{color:#899399}.ps-health{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:8px;padding:10px 12px;border-radius:13px;background:#e8e2d6}.ps-health strong{font-size:9px;letter-spacing:.04em}.ps-health span{font-size:8px;color:#5f625f}.ps-why{margin-top:8px;display:grid;grid-template-columns:1.15fr repeat(3,1fr);gap:7px}.ps-why>div{border-top:1px solid rgba(6,10,13,.18);padding:10px 3px 0}.ps-why b{font-size:9px}.ps-why p{margin:5px 0 0;font-size:8px;line-height:1.45;color:#636764}.ps-why .lead{border-top:3px solid #a17600}.ps-foot{margin:10px 0 0;font-size:6.5px;line-height:1.45;color:#727572}
      @media(max-width:900px){.ps-visuals{grid-template-columns:1.15fr .85fr;grid-template-rows:190px 190px}.ps-numbers{grid-template-columns:repeat(3,1fr)}.ps-stat:nth-child(4),.ps-stat:nth-child(5){grid-column:span 1}.ps-why{grid-template-columns:1fr 1fr}.ps-head{display:block}.ps-head p{text-align:left;margin-top:8px}}
      @media(max-width:620px){.ps{padding:32px 13px}.ps-visuals{grid-template-columns:1fr;grid-template-rows:280px 180px 180px}.ps-card.big{grid-row:auto}.ps-numbers{grid-template-columns:1fr 1fr}.ps-stat:last-child{grid-column:1/-1}.ps-health{display:block}.ps-health span{display:block;margin-top:5px}.ps-why{grid-template-columns:1fr 1fr}.ps-copy h3,.ps-card:not(.big) .ps-copy h3{font-size:25px}.ps-source{font-size:5.5px}}
    `}</style>
    <div className="ps-in">
      <div className="ps-head"><h2>Potensi <em>Subang</em></h2><p>Subang berada di pertemuan pasar penduduk, kawasan industri baru, Pelabuhan Patimban, dan koridor wisata selatan—empat mesin permintaan yang memperluas basis pasien RS Subang Raya.</p></div>      <div className="ps-visuals">
        <article className="ps-card big"><img src={asset('subang-patimban.jpg')} alt="Pelabuhan Patimban di Kabupaten Subang" loading="lazy" decoding="async"/><div className="ps-source">INTERPORT · PATIMBAN</div><div className="ps-copy"><span>GERBANG LOGISTIK NASIONAL</span><h3>Pelabuhan Patimban</h3><p>Terminal kendaraan mencatat 224.935 CBU pada 2023. Pengembangan tahap I diarahkan menuju kapasitas 3,75 juta TEUs dan 600 ribu kendaraan per tahun.</p></div></article>
        <article className="ps-card"><img src={asset('subang-industri.jpg')} alt="Kawasan industri Patimban dan Subang" loading="lazy" decoding="async"/><div className="ps-source">PATIMBAN INDUSTRIAL ESTATE</div><div className="ps-copy"><span>KORIDOR INDUSTRI BARU</span><h3>Ribuan rantai pasok</h3><p>Data kawasan menyebut 1.500+ perusahaan manufaktur rantai pasok di regional Subang; Smartpolitan dikembangkan pada lahan 2.717 ha.</p></div></article>
        <article className="ps-card"><img src={asset('subang-tangkuban.jpg')} alt="Gunung Tangkuban Perahu di kawasan Ciater, Subang" loading="lazy" decoding="async"/><div className="ps-source">WIKIMEDIA COMMONS · CC BY 4.0</div><div className="ps-copy"><span>KORIDOR WISATA SELATAN</span><h3>Ciater · Tangkuban Perahu</h3><p>Daya tarik wisata selatan memperluas arus pengunjung dan aktivitas ekonomi di koridor Subang–Bandung.</p></div></article>
      </div>
      <div className="ps-numbers">
        <div className="ps-stat"><b>1.675.519</b><span>PENDUDUK SUBANG</span><small>Basis populasi BPS 2024</small></div>
        <div className="ps-stat"><b>284.521</b><span>BURUH / KARYAWAN / PEGAWAI</span><small>Pasar tenaga kerja Subang · BPS 2024</small></div>
        <div className="ps-stat dark"><b>1.500+</b><span>MANUFAKTUR RANTAI PASOK</span><small>Data insight regional · Patimban Industrial Estate</small></div>
        <div className="ps-stat"><b>2.717 ha</b><span>SUBANG SMARTPOLITAN</span><small>Kawasan industri, komersial, pendidikan & hunian</small></div>
        <div className="ps-stat"><b>224.935</b><span>CBU VIA PATIMBAN · 2023</span><small>103,18% dari kapasitas terminal kendaraan saat itu · Kemenhub</small></div>
      </div>      <div className="ps-health"><strong>BASIS TENAGA KESEHATAN SUBANG</strong><span><b>629 dokter</b> · 1.842 perawat · 1.232 bidan — indikator Kemenkes/SISDMK.</span></div>
      <div className="ps-why">
        <div className="lead"><b>KENAPA INI PENTING UNTUK RS?</b><p>Permintaan layanan kesehatan tidak hanya datang dari penduduk tetap, tetapi juga pekerja industri, keluarga pekerja, aktivitas logistik, dan pergerakan wisata.</p></div>
        <div><b>PASAR HARIAN</b><p>Populasi besar menciptakan kebutuhan rawat jalan, diagnostik, IGD, rawat inap, dan layanan ibu-anak yang berulang.</p></div>
        <div><b>INDUSTRI & LOGISTIK</b><p>Pertumbuhan kawasan industri dan Patimban memperbesar kebutuhan kesehatan kerja, emergency response, medical check-up, dan layanan korporasi.</p></div>
        <div><b>KORIDOR PERTUMBUHAN</b><p>Rebana–Patimban menempatkan Subang sebagai simpul baru industri, logistik, hunian, dan jasa di Jawa Barat bagian utara.</p></div>
      </div>
      <p className="ps-foot">Sumber data: BPS Kabupaten Subang Dalam Angka 2025; Kemenkes/SISDMK; Kementerian Perhubungan; Investasi Jabar; Patimban Industrial Estate. Foto: Interport, Patimban Industrial Estate, dan Adri45an/Wikimedia Commons (CC BY 4.0). Angka 1.500+ merupakan data insight regional kawasan industri; BPS mencatat 776 perusahaan industri formal/nonformal di Kabupaten Subang pada 2022.</p>
    </div>
  </section>
}
