const kelompok = [
  {nama:'Dokter',total:100,posisi:[['Dokter umum & IGD',28],['Penyakit Dalam',10],['Bedah',10],['Obstetri & Ginekologi',8],['Anak',8],['Anestesi & Intensif',8],['Radiologi',5],['Patologi Klinik/Anatomi',4],['THT-KL',4],['Mata',4],['Saraf',4],['Jantung',4],['Ortopedi',3]]},
  {nama:'Perawat',total:300,posisi:[['Rawat jalan',80],['IGD',36],['Rawat inap',70],['ICU / HCU',40],['Kamar operasi & anestesi',42],['Praoperasi / PACU / bedah sehari',20],['PPI, manajemen kasus & edukasi',12]]},
  {nama:'Penunjang medis',total:100,posisi:[['Farmasi',25],['Laboratorium',22],['Radiologi',18],['Fisioterapi',10],['Gizi',10],['Rekam medis & coding',8],['CSSD',7]]},
  {nama:'Nonklinis & pendukung',total:200,posisi:[['Pendaftaran, front office & pusat layanan',35],['Keuangan, penagihan & kasir',20],['SDM, legal & umum',15],['TI & sistem informasi RS',12],['Teknik, pemeliharaan & utilitas',20],['Kebersihan & sanitasi',35],['Keamanan',24],['Laundry & linen',12],['Pengadaan & gudang',15],['Manajemen, mutu & risiko',12]]},
]

export default function TimOperasional(){
  return <section id="tim-operasional" className="st">
    <style>{`
      .st{background:#081015;color:#fff;padding:24px clamp(14px,3vw,38px);content-visibility:auto;contain-intrinsic-size:460px}.st-in{max-width:1280px;margin:auto}.st-head{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:end}.st-head h2{margin:0;font-size:clamp(30px,4vw,48px);line-height:.88;letter-spacing:-.06em;text-transform:uppercase}.st-head h2 em{font-style:normal;color:#f4c842}.st-head p{margin:7px 0 0;max-width:700px;color:#8f999f;font-size:8.5px;line-height:1.45}.st-total{display:flex;align-items:baseline;gap:9px}.st-total b{font-size:clamp(48px,6vw,76px);line-height:.75;letter-spacing:-.07em;color:#f4c842}.st-total span{font-size:7px;font-weight:950;letter-spacing:.08em;color:#8f999f;white-space:nowrap}
      .st-mix{display:grid;grid-template-columns:1fr 3fr 1fr 2fr;margin-top:12px;height:44px;border-radius:14px;overflow:hidden;border:1px solid rgba(255,255,255,.09);background:#050a0d}.st-mix div{position:relative;display:flex;align-items:center;justify-content:center;gap:5px;border-right:1px solid rgba(255,255,255,.08)}.st-mix div:last-child{border-right:0}.st-mix div:nth-child(2){background:linear-gradient(90deg,rgba(244,200,66,.10),rgba(244,200,66,.18))}.st-mix b{font-size:16px}.st-mix span{font-size:6px;font-weight:950;color:#98a3a8;letter-spacing:.04em}.st-mix div:nth-child(2) b{color:#f4c842}
      .st-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:8px}.st-group{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.085);border-radius:16px;background:linear-gradient(145deg,#0a1318,#071015);padding:11px 12px 12px}.st-group:after{content:attr(data-total);position:absolute;right:8px;bottom:-18px;font-size:92px;font-weight:950;letter-spacing:-.08em;color:rgba(244,200,66,.035);pointer-events:none}.st-group-head{position:relative;z-index:1;display:flex;justify-content:space-between;align-items:center;gap:12px;padding-bottom:7px;margin-bottom:5px;border-bottom:1px solid rgba(255,255,255,.065)}.st-group-head b{font-size:11px;text-transform:uppercase;letter-spacing:.02em}.st-group-head strong{font-size:22px;color:#f4c842;letter-spacing:-.05em}.st-rows{position:relative;z-index:1;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));column-gap:14px}.st-row{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:4px 0;border-bottom:1px solid rgba(255,255,255,.045);min-width:0}.st-row span{font-size:7px;line-height:1.22;color:#bac2c5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.st-row b{font-size:8px;color:#fff;font-variant-numeric:tabular-nums}.st-note{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:8px;padding:7px 10px;border-radius:10px;background:rgba(244,200,66,.055);border-left:2px solid #f4c842}.st-note strong{font-size:7px;color:#f4c842;white-space:nowrap}.st-note span{font-size:7px;color:#8f999f;line-height:1.4}
      @media(max-width:920px){.st-grid{grid-template-columns:1fr 1fr}.st-row span{font-size:6.7px}.st-head{grid-template-columns:1fr}.st-total{margin-top:3px}.st-mix{grid-template-columns:1fr 1.8fr 1fr 1.4fr}}
      @media(max-width:700px){.st{padding:22px 13px}.st-grid{grid-template-columns:1fr}.st-mix{grid-template-columns:1fr 1fr;height:auto}.st-mix div{padding:9px}.st-mix div:nth-child(2){border-right:0}.st-head h2{font-size:30px}.st-total b{font-size:48px}.st-rows{grid-template-columns:1fr 1fr}.st-note{display:block}.st-note span{display:block;margin-top:3px}}
    `}</style>
    <div className="st-in">
      <div className="st-head"><div><h2>Tim <em>Operasional</em></h2><p>Struktur SDM untuk operasi 24/7, 66 posisi pasien, 6 kamar operasi, layanan diagnostik, dan target &gt;2.000 kunjungan per hari.</p></div><div className="st-total"><b>±700</b><span>SDM OPERASIONAL</span></div></div>
      <div className="st-mix"><div><b>100</b><span>DOKTER</span></div><div><b>300</b><span>PERAWAT</span></div><div><b>100</b><span>PENUNJANG</span></div><div><b>200</b><span>NONKLINIS</span></div></div>
      <div className="st-grid">{kelompok.map((grup)=><article className="st-group" data-total={grup.total} key={grup.nama}><div className="st-group-head"><b>{grup.nama}</b><strong>{grup.total}</strong></div><div className="st-rows">{grup.posisi.map(([nama,jumlah])=><div className="st-row" key={nama}><span title={nama}>{nama}</span><b>{jumlah}</b></div>)}</div></article>)}</div>
      <div className="st-note"><strong>500 KLINIS + PENUNJANG · 200 NONKLINIS</strong><span>Komposisi ini merupakan basis rencana tenaga kerja RS Subang Raya untuk cakupan operasi penuh.</span></div>
    </div>
  </section>
}
